[package]
name = "rust-crdt-talk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
chrono = "0.4.40"
clap = { version = "4.5.31", features = ["derive"] }
uuid = "1.15.1"

[dev-dependencies]
proptest = "1.6.0"
proptest-derive = "0.5.1"
